In [2]:
import pandas as pd

df = pd.DataFrame({
    "name": ["Nirdesh", "Asha", "Ram", "Sita", "Asha", "Ram"],
    "age": [22, 25, 21, 24, 25, 21],
    "city": ["Kathmandu", "Pokhara", "Kathmandu", "Lalitpur", "Pokhara", "Biratnagar"],
    "salary": [50000, 60000, 45000, 52000, 60000, 47000],
    "department": ["Data", "HR", "Data", "IT", "HR", "Data"]
})

In [3]:
df.head()

      name  age       city  salary department
0  Nirdesh   22  Kathmandu   50000       Data
1     Asha   25    Pokhara   60000         HR
2      Ram   21  Kathmandu   45000       Data
3     Sita   24   Lalitpur   52000         IT
4     Asha   25    Pokhara   60000         HR

In [4]:
df.tail(3)

   name  age        city  salary department
3  Sita   24    Lalitpur   52000         IT
4  Asha   25     Pokhara   60000         HR
5   Ram   21  Biratnagar   47000       Data

In [5]:
df.columns

Index(['name', 'age', 'city', 'salary', 'department'], dtype='str')

In [6]:
df.shape

(6, 5)

In [8]:
print(df.dtypes)

name            str
age           int64
city            str
salary        int64
department      str
dtype: object

In [9]:
df.describe()

             age        salary
count   6.000000      6.000000
mean   23.000000  52333.333333
std     1.897367   6408.327915
min    21.000000  45000.000000
25%    21.250000  47750.000000
50%    23.000000  51000.000000
75%    24.750000  58000.000000
max    25.000000  60000.000000

In [10]:
df.name

0    Nirdesh
1       Asha
2        Ram
3       Sita
4       Asha
5        Ram
Name: name, dtype: str

In [12]:
print(df[["name", "salary"]])

      name  salary
0  Nirdesh   50000
1     Asha   60000
2      Ram   45000
3     Sita   52000
4     Asha   60000
5      Ram   47000

In [13]:
df['city'].unique()

<StringArray>
['Kathmandu', 'Pokhara', 'Lalitpur', 'Biratnagar']
Length: 4, dtype: str

In [15]:
df['department'].nunique()

3

In [16]:
df[df["salary"]>50000]

   name  age      city  salary department
1  Asha   25   Pokhara   60000         HR
3  Sita   24  Lalitpur   52000         IT
4  Asha   25   Pokhara   60000         HR

In [18]:
df[df["city"]=="Kathmandu"]

      name  age       city  salary department
0  Nirdesh   22  Kathmandu   50000       Data
2      Ram   21  Kathmandu   45000       Data

In [20]:
df[(df['age']>22)&(df['salary']>48000)]

   name  age      city  salary department
1  Asha   25   Pokhara   60000         HR
3  Sita   24  Lalitpur   52000         IT
4  Asha   25   Pokhara   60000         HR

In [24]:
df[df['city'].isin(["Kathmandu","Pokhara"])]

      name  age       city  salary department
0  Nirdesh   22  Kathmandu   50000       Data
1     Asha   25    Pokhara   60000         HR
2      Ram   21  Kathmandu   45000       Data
4     Asha   25    Pokhara   60000         HR

In [25]:
df[df["department"]!='HR']

      name  age        city  salary department
0  Nirdesh   22   Kathmandu   50000       Data
2      Ram   21   Kathmandu   45000       Data
3     Sita   24    Lalitpur   52000         IT
5      Ram   21  Biratnagar   47000       Data