In [1]:
import pandas as pd

In [2]:
data = {
    'id':[1,2,3],
    'name':['ram','shyam','hari'],
    'age':[21,22,24],
    'salary':[1000,2000,4000]
}

In [3]:
df = pd.DataFrame(data)

In [4]:
df

   id   name  age  salary
0   1    ram   21    1000
1   2  shyam   22    2000
2   3   hari   24    4000

In [5]:
df.head(2)

   id   name  age  salary
0   1    ram   21    1000
1   2  shyam   22    2000

In [6]:
df.tail(2)

   id   name  age  salary
1   2  shyam   22    2000
2   3   hari   24    4000

In [7]:
df.shape

(3, 4)

In [8]:
df.columns

Index(['id', 'name', 'age', 'salary'], dtype='str')

In [9]:
df.dtypes

id        int64
name        str
age       int64
salary    int64
dtype: object

In [10]:
df[df['name']]

KeyError: "None of [Index(['ram', 'shyam', 'hari'], dtype='str')] are in the [columns]"

In [11]:
df['name']

0      ram
1    shyam
2     hari
Name: name, dtype: str

In [12]:
df['name','age']

KeyError: ('name', 'age')

In [13]:
df[['name','age']]

    name  age
0    ram   21
1  shyam   22
2   hari   24

In [14]:
df[df['age']>25]

Empty DataFrame
Columns: [id, name, age, salary]
Index: []

In [15]:
df[df['age']>22]

   id  name  age  salary
2   3  hari   24    4000

In [16]:
df['bonus']=df['salary']*0.5

In [17]:
df

   id   name  age  salary   bonus
0   1    ram   21    1000   500.0
1   2  shyam   22    2000  1000.0
2   3   hari   24    4000  2000.0

In [18]:
df.rename(columns={"name":"first_name"}, inplace=True)

In [19]:
df

   id first_name  age  salary   bonus
0   1        ram   21    1000   500.0
1   2      shyam   22    2000  1000.0
2   3       hari   24    4000  2000.0

In [20]:
df.rename(columns={'bonus':"salary_bonus"},inplace=True)

In [21]:
df

   id first_name  age  salary  salary_bonus
0   1        ram   21    1000         500.0
1   2      shyam   22    2000        1000.0
2   3       hari   24    4000        2000.0

In [26]:
df.sort_values(by="salary", ascending=False)

   id first_name  age  salary  salary_bonus
2   3       hari   24    4000        2000.0
1   2      shyam   22    2000        1000.0
0   1        ram   21    1000         500.0

In [28]:
df = pd.read_csv("customers.csv")

In [29]:
df.head()

,customer_id,full_name,city,segment,signup_date,is_active,credit_limit
0,1001,Customer_1,Kathmandu,Retail,2024-04-12,True,25000
1,1002,Customer_2,Lalitpur,SMB,2024-12-14,True,20000
2,1003,Customer_3,Biratnagar,SMB,2024-09-27,True,5000
3,1004,Customer_4,Pokhara,Retail,2024-04-16,True,25000
4,1005,Customer_5,Pokhara,SMB,2024-03-12,True,5000

In [30]:
df.head(10)

,customer_id,full_name,city,segment,signup_date,is_active,credit_limit
0,1001,Customer_1,Kathmandu,Retail,2024-04-12,True,25000
1,1002,Customer_2,Lalitpur,SMB,2024-12-14,True,20000
2,1003,Customer_3,Biratnagar,SMB,2024-09-27,True,5000
3,1004,Customer_4,Pokhara,Retail,2024-04-16,True,25000
4,1005,Customer_5,Pokhara,SMB,2024-03-12,True,5000
5,1006,Customer_6,Kathmandu,Retail,2024-07-07,False,15000
6,1007,Customer_7,Bhaktapur,Retail,2024-01-21,True,5000
7,1008,Customer_8,Kathmandu,Retail,2024-04-12,True,5000
8,1009,Customer_9,Bhaktapur,Retail,2024-05-01,True,5000
9,1010,Customer_10,Pokhara,Retail,2024-08-02,True,20000

In [31]:
df.tail(5)

,customer_id,full_name,city,segment,signup_date,is_active,credit_limit
115,1116,Customer_116,Pokhara,SMB,2024-05-18,False,20000
116,1117,Customer_117,Biratnagar,SMB,2024-03-21,True,5000
117,1118,Customer_118,Bhaktapur,SMB,2025-01-26,True,10000
118,1119,Customer_119,NaN,Enterprise,2024-06-11,True,5000
119,1120,Customer_120,Butwal,Retail,2025-02-22,True,5000

In [32]:
df.tail()

,customer_id,full_name,city,segment,signup_date,is_active,credit_limit
115,1116,Customer_116,Pokhara,SMB,2024-05-18,False,20000
116,1117,Customer_117,Biratnagar,SMB,2024-03-21,True,5000
117,1118,Customer_118,Bhaktapur,SMB,2025-01-26,True,10000
118,1119,Customer_119,NaN,Enterprise,2024-06-11,True,5000
119,1120,Customer_120,Butwal,Retail,2025-02-22,True,5000

In [33]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   customer_id   120 non-null    int64
 1   full_name     120 non-null    str
 2   city          115 non-null    str
 3   segment       120 non-null    str
 4   signup_date   120 non-null    str
 5   is_active     120 non-null    bool
 6   credit_limit  120 non-null    int64
dtypes: bool(1), int64(2), str(4)
memory usage: 5.9 KB

In [34]:
df.describe()

       customer_id  credit_limit
count   120.000000    120.000000
mean   1060.500000  15791.666667
std      34.785054   7503.383924
min    1001.000000   5000.000000
25%    1030.750000  10000.000000
50%    1060.500000  15000.000000
75%    1090.250000  25000.000000
max    1120.000000  25000.000000

In [35]:
kathmandu_user = df[df['city']=='Kathmandu']

In [37]:
kathmandu_user.head()

,customer_id,full_name,city,segment,signup_date,is_active,credit_limit
0,1001,Customer_1,Kathmandu,Retail,2024-04-12,True,25000
5,1006,Customer_6,Kathmandu,Retail,2024-07-07,False,15000
7,1008,Customer_8,Kathmandu,Retail,2024-04-12,True,5000
10,1011,Customer_11,Kathmandu,SMB,2024-11-26,True,5000
18,1019,Customer_19,Kathmandu,Retail,2024-11-04,True,5000

In [40]:
credit = df.sort_values(by="credit_limit",ascending=False)

In [41]:
credit

,customer_id,full_name,city,segment,signup_date,is_active,credit_limit
0,1001,Customer_1,Kathmandu,Retail,2024-04-12,True,25000
106,1107,Customer_107,Pokhara,Enterprise,2024-10-27,True,25000
44,1045,Customer_45,Biratnagar,SMB,2024-05-10,True,25000
90,1091,Customer_91,Bhaktapur,Enterprise,2024-10-22,True,25000
107,1108,Customer_108,Pokhara,Retail,2024-03-05,True,25000
...,...,...,...,...,...,...,...
49,1050,Customer_50,Pokhara,Retail,2024-06-15,False,5000
96,1097,Customer_97,Bhaktapur,Retail,2024-02-22,True,5000
57,1058,Customer_58,Bhaktapur,SMB,2024-12-11,True,5000
53,1054,Customer_54,Kathmandu,Retail,2024-11-11,True,5000
119,1120,Customer_120,Butwal,Retail,2025-02-22,True,5000

In [42]:
df['credit_limit_npr']=df['credit_limit']*0.5

In [43]:
df

,customer_id,full_name,city,segment,signup_date,is_active,credit_limit,credit_limit_npr
0,1001,Customer_1,Kathmandu,Retail,2024-04-12,True,25000,12500.0
1,1002,Customer_2,Lalitpur,SMB,2024-12-14,True,20000,10000.0
2,1003,Customer_3,Biratnagar,SMB,2024-09-27,True,5000,2500.0
3,1004,Customer_4,Pokhara,Retail,2024-04-16,True,25000,12500.0
4,1005,Customer_5,Pokhara,SMB,2024-03-12,True,5000,2500.0
...,...,...,...,...,...,...,...,...
115,1116,Customer_116,Pokhara,SMB,2024-05-18,False,20000,10000.0
116,1117,Customer_117,Biratnagar,SMB,2024-03-21,True,5000,2500.0
117,1118,Customer_118,Bhaktapur,SMB,2025-01-26,True,10000,5000.0
118,1119,Customer_119,NaN,Enterprise,2024-06-11,True,5000,2500.0
119,1120,Customer_120,Butwal,Retail,2025-02-22,True,5000,2500.0

In [44]:
df = pd.read_csv("dirty_orders.csv")

In [45]:
df

     order_id customer_id  order_date channel     status payment_method
0       30861        1116  2024-08-11     Web  Completed           Card
1       30881        1026  14/11/2024     Web    Pending  Bank Transfer
2       30875     unknown  11/06/2024     Web        NaN           Card
3       30781        1060  01-25-2024     App  Completed  Bank Transfer
4       30526        1068  26/08/2024     Web  Completed           Card
..        ...         ...         ...     ...        ...            ...
115     30633        1028  2024-01-04     Web  Completed           Cash
116     30229        1026  2024-01-29     App  Completed  Bank Transfer
117     30805        1098  24/04/2024     Web  Completed  Bank Transfer
118     30048        1078  02-10-2025     App  Completed  Bank Transfer
119     30412        1114  20/01/2024     App  Completed  Bank Transfer

[120 rows x 6 columns]

In [46]:
df.isnull()

     order_id  customer_id  order_date  channel  status  payment_method
0       False        False       False    False   False           False
1       False        False       False    False   False           False
2       False        False       False    False    True           False
3       False        False       False    False   False           False
4       False        False       False    False   False           False
..        ...          ...         ...      ...     ...             ...
115     False        False       False    False   False           False
116     False        False       False    False   False           False
117     False        False       False    False   False           False
118     False        False       False    False   False           False
119     False        False       False    False   False           False

[120 rows x 6 columns]

In [47]:
df.notnull()

     order_id  customer_id  order_date  channel  status  payment_method
0        True         True        True     True    True            True
1        True         True        True     True    True            True
2        True         True        True     True   False            True
3        True         True        True     True    True            True
4        True         True        True     True    True            True
..        ...          ...         ...      ...     ...             ...
115      True         True        True     True    True            True
116      True         True        True     True    True            True
117      True         True        True     True    True            True
118      True         True        True     True    True            True
119      True         True        True     True    True            True

[120 rows x 6 columns]

In [48]:
df

     order_id customer_id  order_date channel     status payment_method
0       30861        1116  2024-08-11     Web  Completed           Card
1       30881        1026  14/11/2024     Web    Pending  Bank Transfer
2       30875     unknown  11/06/2024     Web        NaN           Card
3       30781        1060  01-25-2024     App  Completed  Bank Transfer
4       30526        1068  26/08/2024     Web  Completed           Card
..        ...         ...         ...     ...        ...            ...
115     30633        1028  2024-01-04     Web  Completed           Cash
116     30229        1026  2024-01-29     App  Completed  Bank Transfer
117     30805        1098  24/04/2024     Web  Completed  Bank Transfer
118     30048        1078  02-10-2025     App  Completed  Bank Transfer
119     30412        1114  20/01/2024     App  Completed  Bank Transfer

[120 rows x 6 columns]

In [49]:
df.isnull().sum()

order_id          0
customer_id       0
order_date        0
channel           0
status            5
payment_method    0
dtype: int64

In [50]:
df['status']=df['status'].fillna(0)

In [51]:
df

     order_id customer_id  order_date channel     status payment_method
0       30861        1116  2024-08-11     Web  Completed           Card
1       30881        1026  14/11/2024     Web    Pending  Bank Transfer
2       30875     unknown  11/06/2024     Web          0           Card
3       30781        1060  01-25-2024     App  Completed  Bank Transfer
4       30526        1068  26/08/2024     Web  Completed           Card
..        ...         ...         ...     ...        ...            ...
115     30633        1028  2024-01-04     Web  Completed           Cash
116     30229        1026  2024-01-29     App  Completed  Bank Transfer
117     30805        1098  24/04/2024     Web  Completed  Bank Transfer
118     30048        1078  02-10-2025     App  Completed  Bank Transfer
119     30412        1114  20/01/2024     App  Completed  Bank Transfer

[120 rows x 6 columns]

In [52]:
df.isnull().sum()

order_id          0
customer_id       0
order_date        0
channel           0
status            0
payment_method    0
dtype: int64

In [53]:
df =pd.read_csv("order_items.csv")

In [54]:
df

      order_item_id  order_id  product_id  quantity  unit_price  discount
0                 1     30001        2022         1      320.77      0.00
1                 2     30001        2011         5       71.73      0.20
2                 3     30001        2003         1       76.84      0.05
3                 4     30002        2014         1       40.04      0.00
4                 5     30002        2009         2       80.95      0.05
...             ...       ...         ...       ...         ...       ...
2182            496     30206        2009         4       80.95      0.00
2183            417     30174        2015         5       52.65      0.05
2184           2009     30830        2017         1       86.50      0.05
2185           1728     30708        2033         2      151.34      0.10
2186           1717     30705        2014         5       40.04      0.05

[2187 rows x 6 columns]

In [55]:
df.isna()

      order_item_id  order_id  product_id  quantity  unit_price  discount
0             False     False       False     False       False     False
1             False     False       False     False       False     False
2             False     False       False     False       False     False
3             False     False       False     False       False     False
4             False     False       False     False       False     False
...             ...       ...         ...       ...         ...       ...
2182          False     False       False     False       False     False
2183          False     False       False     False       False     False
2184          False     False       False     False       False     False
2185          False     False       False     False       False     False
2186          False     False       False     False       False     False

[2187 rows x 6 columns]

In [56]:
df.isna().sum()

order_item_id    0
order_id         0
product_id       0
quantity         0
unit_price       0
discount         8
dtype: int64

In [57]:
df.head()

   order_item_id  order_id  product_id  quantity  unit_price  discount
0              1     30001        2022         1      320.77      0.00
1              2     30001        2011         5       71.73      0.20
2              3     30001        2003         1       76.84      0.05
3              4     30002        2014         1       40.04      0.00
4              5     30002        2009         2       80.95      0.05

In [60]:
df["order_data"]=pd.to_datetime(df["order_date"])

KeyError: 'order_date'

In [61]:
df["order_date"] = pd.to_datetime(df["order_date"], errors="coerce", dayfirst=True)

KeyError: 'order_date'

In [62]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
2182     True
2183     True
2184     True
2185     True
2186     True
Length: 2187, dtype: bool

In [63]:
df.duplicated().sum()

np.int64(10)

In [64]:
df.drop_duplicates()

      order_item_id  order_id  product_id  quantity  unit_price  discount
0                 1     30001        2022         1      320.77      0.00
1                 2     30001        2011         5       71.73      0.20
2                 3     30001        2003         1       76.84      0.05
3                 4     30002        2014         1       40.04      0.00
4                 5     30002        2009         2       80.95      0.05
...             ...       ...         ...       ...         ...       ...
2172           2173     30899        2006         1      192.21      0.20
2173           2174     30899        2020         2      277.71      0.10
2174           2175     30899        2013         1       74.92      0.00
2175           2176     30900        2021         1       20.53      0.15
2176           2177     30900        2034         4      196.39      0.05

[2177 rows x 6 columns]

In [65]:
df.duplicated().sum()

np.int64(10)

In [66]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
2182     True
2183     True
2184     True
2185     True
2186     True
Length: 2187, dtype: bool

In [67]:
orders = pd.read_csv("orders.csv")

In [68]:
orders.head()

   order_id  customer_id  order_date channel     status payment_method
0     30001         1065  2024-08-07     App  Completed           Cash
1     30002         1022  2024-03-15     App  Completed  Bank Transfer
2     30003         1090  2024-01-04     App  Completed           Cash
3     30004         1120  2024-11-30     App  Completed  Bank Transfer
4     30005         1082  2024-05-13     Web   Returned           Card

In [70]:
orders['order_date']=pd.to_datetime(orders['order_date'])

In [71]:
orders.head()

   order_id  customer_id order_date channel     status payment_method
0     30001         1065 2024-08-07     App  Completed           Cash
1     30002         1022 2024-03-15     App  Completed  Bank Transfer
2     30003         1090 2024-01-04     App  Completed           Cash
3     30004         1120 2024-11-30     App  Completed  Bank Transfer
4     30005         1082 2024-05-13     Web   Returned           Card

In [72]:
orders.head(5)

   order_id  customer_id order_date channel     status payment_method
0     30001         1065 2024-08-07     App  Completed           Cash
1     30002         1022 2024-03-15     App  Completed  Bank Transfer
2     30003         1090 2024-01-04     App  Completed           Cash
3     30004         1120 2024-11-30     App  Completed  Bank Transfer
4     30005         1082 2024-05-13     Web   Returned           Card

In [73]:
orders.head()

   order_id  customer_id order_date channel     status payment_method
0     30001         1065 2024-08-07     App  Completed           Cash
1     30002         1022 2024-03-15     App  Completed  Bank Transfer
2     30003         1090 2024-01-04     App  Completed           Cash
3     30004         1120 2024-11-30     App  Completed  Bank Transfer
4     30005         1082 2024-05-13     Web   Returned           Card

In [74]:
orders['year']=orders['order_date'].dt.year()

TypeError: 'Series' object is not callable

In [80]:
orders.dtypes

order_id                   int64
customer_id                int64
order_date        datetime64[us]
channel                      str
status                       str
payment_method               str
dtype: object

In [81]:
orders['year']=orders["order_date"].dt.year

In [82]:
orders

     order_id  customer_id order_date channel     status payment_method  year
0       30001         1065 2024-08-07     App  Completed           Cash  2024
1       30002         1022 2024-03-15     App  Completed  Bank Transfer  2024
2       30003         1090 2024-01-04     App  Completed           Cash  2024
3       30004         1120 2024-11-30     App  Completed  Bank Transfer  2024
4       30005         1082 2024-05-13     Web   Returned           Card  2024
..        ...          ...        ...     ...        ...            ...   ...
895     30896         1111 2024-01-12     App  Completed           Card  2024
896     30897         1049 2025-02-09     Web  Completed  Bank Transfer  2025
897     30898         1042 2025-02-04   Store  Completed           Cash  2025
898     30899         1038 2025-01-28     Web  Completed  Bank Transfer  2025
899     30900         1082 2025-01-08     Web    Pending           Cash  2025

[900 rows x 7 columns]

In [83]:
orders.groupby(orders['order_date'].dt.month)['order_id'].count()

order_date
1     122
2     116
3     105
4      60
5      60
6      68
7      46
8      68
9      53
10     70
11     71
12     61
Name: order_id, dtype: int64

In [84]:
orders.groupby(orders['order_date'].dt.month)['order_id'].count()

order_date
1     122
2     116
3     105
4      60
5      60
6      68
7      46
8      68
9      53
10     70
11     71
12     61
Name: order_id, dtype: int64

In [86]:
orders[orders['order_date']>'2024-02-01']

     order_id  customer_id order_date channel     status payment_method  year
0       30001         1065 2024-08-07     App  Completed           Cash  2024
1       30002         1022 2024-03-15     App  Completed  Bank Transfer  2024
3       30004         1120 2024-11-30     App  Completed  Bank Transfer  2024
4       30005         1082 2024-05-13     Web   Returned           Card  2024
5       30006         1050 2024-04-27     Web  Completed         Wallet  2024
..        ...          ...        ...     ...        ...            ...   ...
893     30894         1106 2024-07-10     Web  Cancelled           Card  2024
896     30897         1049 2025-02-09     Web  Completed  Bank Transfer  2025
897     30898         1042 2025-02-04   Store  Completed           Cash  2025
898     30899         1038 2025-01-28     Web  Completed  Bank Transfer  2025
899     30900         1082 2025-01-08     Web    Pending           Cash  2025

[832 rows x 7 columns]

In [87]:
orders.sort_values("order_date")

     order_id  customer_id order_date channel     status payment_method  year
31      30032         1029 2024-01-01     Web  Completed  Bank Transfer  2024
243     30244         1115 2024-01-01     Web  Cancelled           Card  2024
80      30081         1012 2024-01-01     Web  Completed           Cash  2024
400     30401         1113 2024-01-02     App  Completed  Bank Transfer  2024
754     30755         1019 2024-01-03     App  Completed  Bank Transfer  2024
..        ...          ...        ...     ...        ...            ...   ...
440     30441         1050 2025-03-25     App  Completed           Card  2025
642     30643         1077 2025-03-25     Web  Completed           Card  2025
534     30535         1082 2025-03-25     Web   Returned           Card  2025
125     30126         1118 2025-03-25     Web  Completed           Cash  2025
859     30860         1038 2025-03-25   Store  Completed           Cash  2025

[900 rows x 7 columns]

In [88]:
orders['order_date'].max()

Timestamp('2025-03-25 00:00:00')

In [89]:
orders['order_date'].max()-orders['order_date'].min()

Timedelta('449 days 00:00:00')

In [90]:
orders['month']=orders['order_date'].dt.month

In [91]:
orders

,order_id,customer_id,order_date,channel,status,payment_method,year,month
0,30001,1065,2024-08-07,App,Completed,Cash,2024,8
1,30002,1022,2024-03-15,App,Completed,Bank Transfer,2024,3
2,30003,1090,2024-01-04,App,Completed,Cash,2024,1
3,30004,1120,2024-11-30,App,Completed,Bank Transfer,2024,11
4,30005,1082,2024-05-13,Web,Returned,Card,2024,5
...,...,...,...,...,...,...,...,...
895,30896,1111,2024-01-12,App,Completed,Card,2024,1
896,30897,1049,2025-02-09,Web,Completed,Bank Transfer,2025,2
897,30898,1042,2025-02-04,Store,Completed,Cash,2025,2
898,30899,1038,2025-01-28,Web,Completed,Bank Transfer,2025,1
899,30900,1082,2025-01-08,Web,Pending,Cash,2025,1