In [69]:
import pandas as pd

In [70]:
toyata_data = pd.read_csv("data-main/car_sales/toyota_sales_data_no_header.csv")

In [71]:
toyata_data.head

<bound method NDFrame.head of          1  16  2024-11-18   Tundra  44496.88  0.05  Completed
0        2  11  2024-11-08   Tacoma  34824.72   NaN    Pending
1        3   5  2024-11-03  Corolla  20275.08   NaN  Completed
2        4  20  2024-11-06  Corolla  20068.93   NaN  Completed
3        5   1  2024-11-26   Tundra  49811.99  0.03  Completed
4        6  14  2024-11-28     RAV4  34346.20  0.03  Completed
...    ...  ..         ...      ...       ...   ...        ...
4994  4996   1  2024-11-06  Corolla  21484.83  0.05  Completed
4995  4997   8  2024-11-11    Camry  26519.24  0.05    Pending
4996  4998  18  2024-11-06   Tacoma  30780.39  0.02  Completed
4997  4999  10  2024-11-21  Corolla  22654.59   NaN  Completed
4998  5000  13  2024-11-21   Tundra  44525.85   NaN  Cancelled

[4999 rows x 7 columns]>

In [72]:
toyata_data.head()

   1  16  2024-11-18   Tundra  44496.88  0.05  Completed
0  2  11  2024-11-08   Tacoma  34824.72   NaN    Pending
1  3   5  2024-11-03  Corolla  20275.08   NaN  Completed
2  4  20  2024-11-06  Corolla  20068.93   NaN  Completed
3  5   1  2024-11-26   Tundra  49811.99  0.03  Completed
4  6  14  2024-11-28     RAV4  34346.20  0.03  Completed

In [73]:
toyata_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 4999 entries, 0 to 4998
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   1           4999 non-null   int64
 1   16          4999 non-null   int64
 2   2024-11-18  4999 non-null   str
 3   Tundra      4999 non-null   str
 4   44496.88    4999 non-null   float64
 5   0.05        3725 non-null   float64
 6   Completed   4999 non-null   str
dtypes: float64(2), int64(2), str(3)
memory usage: 273.5 KB

In [74]:
toyata_data.shape()

TypeError: 'tuple' object is not callable

In [ ]:
toyata_data.shape

(4999, 7)

In [ ]:
toyata_data.columns

Index(['1', '16', '2024-11-18', 'Tundra', '44496.88', '0.05', 'Completed'], dtype='str')

In [ ]:
toyata_data = pd.read_csv("data-main/car_sales/toyota_sales_data.csv")

In [ ]:
toyata_data.columns

Index(['sale_id', 'sale_rep_id', 'sale_date', 'car_model', 'sale_amount',
       'commission_pct', 'sale_status'],
      dtype='str')

In [ ]:
toyata_data.columns.to_list()

['sale_id',
 'sale_rep_id',
 'sale_date',
 'car_model',
 'sale_amount',
 'commission_pct',
 'sale_status']

In [ ]:
toyata_data.dtypes()

TypeError: 'Series' object is not callable

In [ ]:
toyata_data.dtypes

sale_id             int64
sale_rep_id         int64
sale_date             str
car_model             str
sale_amount       float64
commission_pct    float64
sale_status           str
dtype: object

In [ ]:
help(pd.read_csv)

Help on function read_csv in module pandas:

read_csv(
    filepath_or_buffer: FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str],
    *,
    sep: str | None | lib.NoDefault = <no_default>,
    delimiter: str | None | lib.NoDefault = None,
    header: int | Sequence[int] | None | Literal['infer'] = 'infer',
    names: Sequence[Hashable] | None | lib.NoDefault = <no_default>,
    index_col: IndexLabel | Literal[False] | None = None,
    usecols: UsecolsArgType = None,
    dtype: DtypeArg | None = None,
    engine: CSVEngine | None = None,
    converters: Mapping[HashableT, Callable] | None = None,
    true_values: list | None = None,
    false_values: list | None = None,
    skipinitialspace: bool = False,
    skiprows: list[int] | int | Callable[[Hashable], bool] | None = None,
    skipfooter: int = 0,
    nrows: int | None = None,
    na_values: Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None = None,
    keep_default_na: bool = True,
    na_filter: bool = True,
    skip_blank_lines: bool = True,
    parse_dates: bool | Sequence[Hashable] | None = None,
    date_format: str | dict[Hashable, str] | None = None,
    dayfirst: bool = False,
    cache_dates: bool = True,
    iterator: bool = False,
    chunksize: int | None = None,
    compression: CompressionOptions = 'infer',
    thousands: str | None = None,
    decimal: str = '.',
    lineterminator: str | None = None,
    quotechar: str = '"',
    quoting: int = 0,
    doublequote: bool = True,
    escapechar: str | None = None,
    comment: str | None = None,
    encoding: str | None = None,
    encoding_errors: str | None = 'strict',
    dialect: str | csv.Dialect | None = None,
    on_bad_lines: str = 'error',
    low_memory: bool = True,
    memory_map: bool = False,
    float_precision: Literal['high', 'legacy', 'round_trip'] | None = None,
    storage_options: StorageOptions | None = None,
    dtype_backend: DtypeBackend | lib.NoDefault = <no_default>
) -> DataFrame | TextFileReader
    Read a comma-separated values (csv) file into DataFrame.

    Also supports optionally iterating or breaking of the file
    into chunks.

    Additional help can be found in the online docs for
    `IO Tools <https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html>`_.

    Parameters
    ----------
    filepath_or_buffer : str, path object or file-like object
        Any valid string path is acceptable. The string could be a URL. Valid
        URL schemes include http, ftp, s3, gs, and file. For file URLs, a host is
        expected. A local file could be: file://localhost/path/to/table.csv.

        If you want to pass in a path object, pandas accepts any ``os.PathLike``.

        By file-like object, we refer to objects with a ``read()`` method, such as
        a file handle (e.g. via builtin ``open`` function) or ``StringIO``.
    sep : str, default ','
        Character or regex pattern to treat as the delimiter. If ``sep=None``, the
        C engine cannot automatically detect
        the separator, but the Python parsing engine can, meaning the latter will
        be used and automatically detect the separator from only the first valid
        row of the file by Python's builtin sniffer tool, ``csv.Sniffer``.
        In addition, separators longer than 1 character and different from
        ``'\s+'`` will be interpreted as regular expressions and will also force
        the use of the Python parsing engine. Note that regex delimiters are prone
        to ignoring quoted data. Regex example: ``'\r\t'``.
    delimiter : str, optional
        Alias for ``sep``.
    header : int, Sequence of int, 'infer' or None, default 'infer'
        Row number(s) containing column labels and marking the start of the
        data (zero-indexed). Default behavior is to infer the column names:
        if no ``names``
        are passed the behavior is identical to ``header=0`` and column
        names are inferred from the first line of the file, if column
        names are passed explicitly to ``names`` then the behavior is identical to
        ``header=None``. Explicitly pass ``header=0`` to be able to
        replace existing names. The header can be a list of integers that
        specify row locations for a :class:`~pandas.MultiIndex` on the columns
        e.g. ``[0, 1, 3]``. Intervening rows that are not specified will be
        skipped (e.g. 2 in this example is skipped). Note that this
        parameter ignores commented lines and empty lines if
        ``skip_blank_lines=True``, so ``header=0`` denotes the first line of
        data rather than the first line of the file.

        When inferred from the file contents, headers are kept distinct from
        each other by renaming duplicate names with a numeric suffix of the form
        ``".{{count}}"`` starting from 1, e.g. ``"foo"`` and ``"foo.1"``.
        Empty headers are named ``"Unnamed: {{i}}"`` or ``
        "Unnamed: {{i}}_level_{{level}}"``
        in the case of MultiIndex columns.
    names : Sequence of Hashable, optional
        Sequence of column labels to apply. If the file contains a header row,
        then you should explicitly pass ``header=0`` to override the column names.
        Duplicates in this list are not allowed.
    index_col : Hashable, Sequence of Hashable or False, optional
        Column(s) to use as row label(s), denoted either by column labels or column
        indices.  If a sequence of labels or indices is given,
        :class:`~pandas.MultiIndex`
        will be formed for the row labels.

        Note: ``index_col=False`` can be used to force pandas to *not* use the first
        column as the index, e.g., when you have a malformed file with delimiters at
        the end of each line.
    usecols : Sequence of Hashable or Callable, optional
        Subset of columns to select, denoted either
        by column labels or column indices.
        If list-like, all elements must either
        be positional (i.e. integer indices into the document columns) or strings
        that correspond to column names provided either by the user in ``names`` or
        inferred from the document header row(s).
        If ``names`` are given, the document
        header row(s) are not taken into account. For example, a valid list-like
        ``usecols`` parameter would be ``[0, 1, 2]`` or ``['foo', 'bar', 'baz']``.
        Element order is ignored, so ``usecols=[0, 1]`` is the same as ``[1, 0]``.
        To instantiate a :class:`~pandas.DataFrame` from ``data`` with element order
        preserved use ``pd.read_csv(data, usecols=['foo', 'bar'])[['foo', 'bar']]``
        for columns in ``['foo', 'bar']`` order or
        ``pd.read_csv(data, usecols=['foo', 'bar'])[['bar', 'foo']]``
        for ``['bar', 'foo']`` order.

        If callable, the callable function will be evaluated against the column
        names, returning names where the callable function evaluates to ``True``. An
        example of a valid callable argument would be ``lambda x: x.upper() in
        ['AAA', 'BBB', 'DDD']``. Using this parameter results in much faster
        parsing time and lower memory usage.
    dtype : dtype or dict of {{Hashable : dtype}}, optional
        Data type(s) to apply to either the whole dataset or individual columns.
        E.g., ``{{'a': np.float64, 'b': np.int32, 'c': 'Int64'}}``
        Use ``str`` or ``object`` together with suitable ``na_values`` settings
        to preserve and not interpret ``dtype``.
        If ``converters`` are specified, they will be applied INSTEAD
        of ``dtype`` conversion. Specify a ``defaultdict`` as input where
        the default determines the ``dtype``
        of the columns which are not explicitly
        listed.
    engine : {{'c', 'python', 'pyarrow'}}, optional
        Parser engine to use. The C and pyarrow engines are faster,
        while the python engine
        is currently more feature-complete. Multithreading
        is currently only supported by
        the pyarrow engine. Some features of the "pyarrow" engine
        are unsupported or may not work correctly.
    converters : dict of {{Hashable : Callable}}, optional
        Functions for converting values in specified columns. Keys can either
        be column labels or column indices.
    true_values : list, optional
        Values to consider as ``True`` in addition
        to case-insensitive variants of 'True'.
    false_values : list, optional
        Values to consider as ``False`` in addition to case-insensitive
        variants of 'False'.
    skipinitialspace : bool, default False
        Skip spaces after delimiter.
    skiprows : int, list of int or Callable, optional
        Line numbers to skip (0-indexed) or number of lines to skip (``int``)
        at the start of the file.

        If callable, the callable function will be evaluated against the row
        indices, returning ``True`` if the row should be skipped and ``False``
        otherwise.
        An example of a valid callable argument would be ``lambda x: x in [0, 2]``.
    skipfooter : int, default 0
        Number of lines at bottom of file to skip (Unsupported with ``engine='c'``).
    nrows : int, optional
        Number of rows of file to read. Useful for reading pieces of large files.
        Refers to the number of data rows in the returned DataFrame, excluding:

        * The header row containing column names.
        * Rows before the header row, if ``header=1`` or larger.

        Example usage:

        * To read the first 999,999 (non-header) rows:
          ``read_csv(..., nrows=999999)``

        * To read rows 1,000,000 through 1,999,999:
          ``read_csv(..., skiprows=1000000, nrows=999999)``

    na_values : Hashable, Iterable of Hashable or dict of {{Hashable : Iterable}},
        optional
        Additional strings to recognize as ``NA``/``NaN``. If ``dict``
        passed, specific
        per-column ``NA`` values.  By default the following values
        are interpreted as
        ``NaN``: empty string, "NaN", "N/A", "NULL", and other common
        representations of missing data.
    keep_default_na : bool, default True
        Whether or not to include the default ``NaN`` values when parsing the data.
        Depending on whether ``na_values`` is passed in, the behavior is as follows:

        * If ``keep_default_na`` is ``True``, and ``na_values``
          are specified, ``na_values``
          is appended to the default ``NaN`` values used for parsing.
        * If ``keep_default_na`` is ``True``, and ``na_values`` are not specified, only
          the default ``NaN`` values are used for parsing.
        * If ``keep_default_na`` is ``False``, and ``na_values`` are specified, only
          the ``NaN`` values specified ``na_values`` are used for parsing.
        * If ``keep_default_na`` is ``False``, and ``na_values`` are not specified, no
          strings will be parsed as ``NaN``.

        Note that if ``na_filter`` is passed in as ``False``,
        the ``keep_default_na`` and
        ``na_values`` parameters will be ignored.
    na_filter : bool, default True
        Detect missing value markers (empty strings and the value of ``na_values``). In
        data without any ``NA`` values, passing ``na_filter=False`` can improve the
        performance of reading a large file.
    skip_blank_lines : bool, default True
        If ``True``, skip over blank lines rather than interpreting as ``NaN`` values.
    parse_dates : bool, None, list of Hashable, default None
        The behavior is as follows:

        * ``bool``. If ``True`` -> try parsing the index.
        * ``None``. Behaves like ``True`` if ``date_format`` is specified.
        * ``list`` of ``int`` or names.
          e.g. If ``[1, 2, 3]`` -> try parsing columns 1, 2, 3
          each as a separate date column.

        If a column or index cannot be represented as an array of ``datetime``,
        say because of an unparsable value or a mixture of timezones, the column
        or index will be returned unaltered as an ``object`` data type. For
        non-standard ``datetime`` parsing, use :func:`~pandas.to_datetime` after
        :func:`~pandas.read_csv`.

        Note: A fast-path exists for iso8601-formatted dates.
    date_format : str or dict of column -> format, optional
        Format to use for parsing dates and/or times when
        used in conjunction with ``parse_dates``.
        The strftime to parse time, e.g. :const:`"%d/%m/%Y"`. See
        `strftime documentation
        <https://docs.python.org/3/library/datetime.html
        #strftime-and-strptime-behavior>`_ for more information on choices, though
        note that :const:`"%f"`` will parse all the way up to nanoseconds.
        You can also pass:

        - "ISO8601", to parse any `ISO8601 <https://en.wikipedia.org/wiki/ISO_8601>`_
          time string (not necessarily in exactly the same format);
        - "mixed", to infer the format for each element individually. This is risky,
          and you should probably use it along with `dayfirst`.

        .. versionadded:: 2.0.0
    dayfirst : bool, default False
        DD/MM format dates, international and European format.
    cache_dates : bool, default True
        If ``True``, use a cache of unique, converted dates to apply the ``datetime``
        conversion. May produce significant speed-up when parsing duplicate
        date strings, especially ones with timezone offsets.

    iterator : bool, default False
        Return ``TextFileReader`` object for iteration or getting chunks with
        ``get_chunk()``.
    chunksize : int, optional
        Number of lines to read from the file per chunk. Passing a value will cause the
        function to return a ``TextFileReader`` object for iteration.
        See the `IO Tools docs
        <https://pandas.pydata.org/pandas-docs/stable/io.html#io-chunking>`_
        for more information on ``iterator`` and ``chunksize``.

    compression : str or dict, default 'infer'
        For on-the-fly decompression of on-disk data.
        If 'infer' and 'filepath_or_buffer' is
        path-like, then detect compression from the following extensions: '.gz',
        '.bz2', '.zip', '.xz', '.zst', '.tar', '.tar.gz', '.tar.xz' or '.tar.bz2'
        (otherwise no compression).
        If using 'zip' or 'tar', the ZIP file must contain only
        one data file to be read in.
        Set to ``None`` for no decompression.
        Can also be a dict with key ``'method'`` set
        to one of {``'zip'``, ``'gzip'``, ``'bz2'``,
        ``'zstd'``, ``'xz'``, ``'tar'``} and
        other key-value pairs are forwarded to
        ``zipfile.ZipFile``, ``gzip.GzipFile``,
        ``bz2.BZ2File``, ``zstandard.ZstdDecompressor``, ``lzma.LZMAFile`` or
        ``tarfile.TarFile``, respectively.
        As an example, the following could be passed for
        Zstandard decompression using a
        custom compression dictionary:
        ``compression={'method': 'zstd', 'dict_data': my_compression_dict}``.

    thousands : str (length 1), optional
        Character acting as the thousands separator in numerical values.
    decimal : str (length 1), default '.'
        Character to recognize as decimal point (e.g., use ',' for European data).
    lineterminator : str (length 1), optional
        Character used to denote a line break. Only valid with C parser.
    quotechar : str (length 1), optional
        Character used to denote the start and end of a quoted item. Quoted
        items can include the ``delimiter`` and it will be ignored.
    quoting : {{0 or csv.QUOTE_MINIMAL, 1 or csv.QUOTE_ALL,
        2 or csv.QUOTE_NONNUMERIC, 3 or csv.QUOTE_NONE}}, default csv.QUOTE_MINIMAL
        Control field quoting behavior per ``csv.QUOTE_*`` constants. Default is
        ``csv.QUOTE_MINIMAL`` (i.e., 0) which implies that
        only fields containing special
        characters are quoted (e.g., characters defined
        in ``quotechar``, ``delimiter``,
        or ``lineterminator``.
    doublequote : bool, default True
        When ``quotechar`` is specified and ``quoting`` is not ``QUOTE_NONE``, indicate
        whether or not to interpret two consecutive ``quotechar`` elements INSIDE a
        field as a single ``quotechar`` element.
    escapechar : str (length 1), optional
        Character used to escape other characters.
    comment : str (length 1), optional
        Character indicating that the remainder of line should not be parsed.
        If found at the beginning
        of a line, the line will be ignored altogether. This parameter must be a
        single character. Like empty lines (as long as ``skip_blank_lines=True``),
        fully commented lines are ignored by the parameter ``header`` but not by
        ``skiprows``. For example, if ``comment='#'``, parsing
        ``#empty\na,b,c\n1,2,3`` with ``header=0`` will result in ``'a,b,c'`` being
        treated as the header.
    encoding : str, optional, default 'utf-8'
        Encoding to use for UTF when reading/writing (ex. ``'utf-8'``). `List of Python
        standard encodings
        <https://docs.python.org/3/library/codecs.html#standard-encodings>`_ .

    encoding_errors : str, optional, default 'strict'
        How encoding errors are treated. `List of possible values
        <https://docs.python.org/3/library/codecs.html#error-handlers>`_ .

    dialect : str or csv.Dialect, optional
        If provided, this parameter will override values (default or not) for the
        following parameters: ``delimiter``, ``doublequote``, ``escapechar``,
        ``skipinitialspace``, ``quotechar``, and ``quoting``. If it is necessary to
        override values, a ``ParserWarning`` will be issued. See ``csv.Dialect``
        documentation for more details.
    on_bad_lines : {{'error', 'warn', 'skip'}} or Callable, default 'error'
        Specifies what to do upon encountering a bad line (a line with too many fields).
        Allowed values are:

        - ``'error'``, raise an Exception when a bad line is encountered.
        - ``'warn'``, raise a warning when a bad line is
          encountered and skip that line.
        - ``'skip'``, skip bad lines without raising or warning when
          they are encountered.
        - Callable, function that will process a single bad line.
            - With ``engine='python'``, function with signature
              ``(bad_line: list[str]) -> list[str] | None``.
              ``bad_line`` is a list of strings split by the ``sep``.
              If the function returns ``None``, the bad line will be ignored.
              If the function returns a new ``list`` of strings with
              more elements than
              expected, a ``ParserWarning`` will be emitted while
              dropping extra elements.
            - With ``engine='pyarrow'``, function with signature
              as described in pyarrow documentation: `invalid_row_handler
              <https://arrow.apache.org/docs/python
              /generated/pyarrow.csv.ParseOptions.html
              #pyarrow.csv.ParseOptions.invalid_row_handler>`_.

        .. versionchanged:: 2.2.0

            Callable for ``engine='pyarrow'``

    low_memory : bool, default True
        Internally process the file in chunks, resulting in lower memory use
        while parsing, but possibly mixed type inference.  To ensure no mixed
        types either set ``False``, or specify the type with the ``dtype`` parameter.
        Note that the entire file is read into a single :class:`~pandas.DataFrame`
        regardless, use the ``chunksize`` or ``iterator``
        parameter to return the data in
        chunks. (Only valid with C parser).
    memory_map : bool, default False
        If a filepath is provided for ``filepath_or_buffer``, map the file object
        directly onto memory and access the data directly from there. Using this

In [ ]:
toyata_data = pd.read_csv("data-main/car_sales/toyota_sales_data_no_header.csv",
                          delimiter=',',
                          header=None,
                          names=["sale_id","sale_rep_id","sale_date","car_model","sale_amount","commission_pct","sale_status","commission_amount"
])

In [ ]:
toyata_data.head()

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status,commission_amount
0,1,16,2024-11-18,Tundra,44496.88,0.05,Completed,NaN
1,2,11,2024-11-08,Tacoma,34824.72,NaN,Pending,NaN
2,3,5,2024-11-03,Corolla,20275.08,NaN,Completed,NaN
3,4,20,2024-11-06,Corolla,20068.93,NaN,Completed,NaN
4,5,1,2024-11-26,Tundra,49811.99,0.03,Completed,NaN

In [96]:
toyata_data_chunk = pd.read_csv("data-main/car_sales/toyota_sales_data_no_header.csv",
                                names=["sale_id","sale_rep_id","sale_date","car_model","sale_amount","commission_pct","sale_status","commission_amount"],
                          chunksize=100)

In [93]:
type(toyata_data_chunk)

pandas.io.parsers.readers.TextFileReader

In [94]:
for toyata_chunk in toyata_data_chunk:
    print(toyata_chunk.head())

   sale_id  sale_rep_id   sale_date car_model  sale_amount  commission_pct  \
0        1           16  2024-11-18    Tundra     44496.88            0.05
1        2           11  2024-11-08    Tacoma     34824.72             NaN
2        3            5  2024-11-03   Corolla     20275.08             NaN
3        4           20  2024-11-06   Corolla     20068.93             NaN
4        5            1  2024-11-26    Tundra     49811.99            0.03

  sale_status  commission_amount
0   Completed                NaN
1     Pending                NaN
2   Completed                NaN
3   Completed                NaN
4   Completed                NaN
     sale_id  sale_rep_id   sale_date   car_model  sale_amount  \
100      101            7  2024-11-13        RAV4     32219.86
101      102            2  2024-11-01      Tacoma     36531.02
102      103            6  2024-11-04  Highlander     39423.27
103      104           13  2024-11-01  Highlander     38543.89
104      105            2  2024-11-12      Tacoma     34122.47

     commission_pct sale_status  commission_amount
100            0.03     Pending                NaN
101             NaN   Completed                NaN
102            0.02   Cancelled                NaN
103            0.05   Completed                NaN
104             NaN   Completed                NaN
     sale_id  sale_rep_id   sale_date   car_model  sale_amount  \
200      201            9  2024-11-10       Camry     26339.37
201      202           20  2024-11-11  Highlander     40517.24
202      203           19  2024-11-18        RAV4     34245.12
203      204            5  2024-11-01        RAV4     34529.56
204      205           13  2024-11-21        RAV4     34392.53

     commission_pct sale_status  commission_amount
200             NaN   Cancelled                NaN
201            0.03   Completed                NaN
202            0.03   Completed                NaN
203            0.03   Completed                NaN
204            0.05     Pending                NaN
     sale_id  sale_rep_id   sale_date car_model  sale_amount  commission_pct  \
300      301            2  2024-11-15     Camry     26249.79             NaN
301      302           18  2024-11-01    Tundra     46279.17            0.03
302      303           15  2024-11-17   Corolla     20934.30             NaN
303      304            9  2024-11-17      RAV4     28249.37             NaN
304      305           16  2024-11-14      RAV4     32867.17            0.05

    sale_status  commission_amount
300   Cancelled                NaN
301   Completed                NaN
302   Completed                NaN
303   Completed                NaN
304   Completed                NaN
     sale_id  sale_rep_id   sale_date   car_model  sale_amount  \
400      401           20  2024-11-08      Tacoma     37829.94
401      402           15  2024-11-21     Corolla     22046.96
402      403            2  2024-11-03  Highlander     43701.27
403      404            5  2024-11-12     Corolla     20220.42
404      405            4  2024-11-11        RAV4     34218.51

     commission_pct sale_status  commission_amount
400            0.03   Completed                NaN
401            0.02     Pending                NaN
402            0.05   Completed                NaN
403            0.05     Pending                NaN
404            0.05   Completed                NaN
     sale_id  sale_rep_id   sale_date   car_model  sale_amount  \
500      501           16  2024-11-11      Tacoma     33515.35
501      502            2  2024-11-09  Highlander     35071.08
502      503            8  2024-11-01        RAV4     34498.34
503      504            2  2024-11-15      Tacoma     34479.83
504      505           11  2024-11-11      Tacoma     39145.84

     commission_pct sale_status  commission_amount
500            0.03   Completed                NaN
501            0.05   Completed                NaN
502            0.05   Completed                NaN
503             NaN   Completed                NaN
504            0.03   Completed                NaN
     sale_id  sale_rep_id   sale_date   car_model  sale_amount  \
600      601            4  2024-11-28     Corolla     24866.00
601      602           13  2024-11-19        RAV4     33439.65
602      603            5  2024-11-05  Highlander     42125.82
603      604           20  2024-11-06  Highlander     42302.20
604      605           14  2024-11-26     Corolla     23486.71

     commission_pct sale_status  commission_amount
600            0.05   Completed                NaN
601            0.05   Completed                NaN
602            0.05   Completed                NaN
603            0.05   Completed                NaN
604             NaN     Pending                NaN
     sale_id  sale_rep_id   sale_date   car_model  sale_amount  \
700      701           11  2024-11-06  Highlander     44864.78
701      702           12  2024-11-10        RAV4     30350.62
702      703           20  2024-11-10      Tundra     37167.28
703      704           11  2024-11-10        RAV4     30375.58
704      705           18  2024-11-06     Corolla     22956.19

     commission_pct sale_status  commission_amount
700             NaN   Completed                NaN
701            0.02   Completed                NaN
702             NaN   Completed                NaN
703             NaN     Pending                NaN
704            0.03   Completed                NaN
     sale_id  sale_rep_id   sale_date   car_model  sale_amount  \
800      801           18  2024-11-19      Tundra     49020.28
801      802           20  2024-11-18       Camry     29267.04
802      803            1  2024-11-09      Tacoma     36407.58
803      804            6  2024-11-25  Highlander     44077.69
804      805           13  2024-11-11  Highlander     39608.26

     commission_pct sale_status  commission_amount
800            0.03   Completed                NaN
801            0.03     Pending                NaN
802            0.03     Pending                NaN
803             NaN     Pending                NaN
804             NaN   Completed                NaN
     sale_id  sale_rep_id   sale_date car_model  sale_amount  commission_pct  \
900      901            2  2024-11-28     Camry     25700.31             NaN
901      902           16  2024-11-05   Corolla     23437.32            0.05
902      903           15  2024-11-27    Tacoma     31365.19            0.02
903      904           10  2024-11-04    Tundra     43019.93            0.03
904      905            9  2024-11-12   Corolla     23309.34            0.02

    sale_status  commission_amount
900     Pending                NaN
901   Completed                NaN
902   Completed                NaN
903   Cancelled                NaN
904   Completed                NaN
      sale_id  sale_rep_id   sale_date   car_model  sale_amount  \
1000     1001           20  2024-11-08       Camry     27774.90
1001     1002            6  2024-11-02      Tundra     49823.29
1002     1003            7  2024-11-06  Highlander     36224.40
1003     1004            6  2024-11-21      Tundra     43133.05
1004     1005            1  2024-11-28       Camry     28852.21

      commission_pct sale_status  commission_amount
1000            0.05   Completed                NaN
1001            0.05   Completed                NaN
1002             NaN   Completed                NaN
1003            0.02   Completed                NaN
1004            0.05     Pending                NaN
      sale_id  sale_rep_id   sale_date car_model  sale_amount  commission_pct  \
1100     1101            3  2024-11-12     Camry     28573.57             NaN
1101     1102            8  2024-11-10      RAV4     31084.65            0.02
1102     1103           12  2024-11-17    Tundra     45353.37            0.03
1103     1104            2  2024-11-07    Tundra     35679.36            0.02
1104     1105           10  2024-11-10    Tundra     36296.36            0.05

     sale_status  commission_amount
1100   Completed                NaN
1101   Completed                NaN
1102   Completed                NaN
1103     Pending                NaN
1104   Completed                NaN
      sale_id  sale_rep_id   sale_date car_model  sale_amount  commission_pct  \
1200     1201            4  2024-11-28   Corolla     20342.27            0.03
1201     1202           15  2024-11-20     Camry     25486.31            0.05
1202     1203            3  2024-11-06    Tacoma     35010.72            0.03
1203     1204            7  2024-11-15     Camry     25794.73            0.05
1204     1205           12  2024-11-19     Camry     29471.63            0.03

     sale_status  commission_amount
1200   Completed                NaN
1201   Completed                NaN
1202   Completed                NaN
1203   Completed                NaN
1204   Completed                NaN
      sale_id  sale_rep_id   sale_date   car_model  sale_amount  \
1300     1301           12  2024-11-21      Tundra     35114.87
1301     1302           17  2024-11-26        RAV4     31323.50
1302     1303            6  2024-11-08  Highlander     39615.09
1303     1304            2  2024-11-15        RAV4     33358.30
1304     1305           12  2024-11-06      Tacoma     38039.67

      commission_pct sale_status  commission_amount
1300             NaN   Completed                NaN
1301            0.02   Completed                NaN
1302            0.03   Completed                NaN
1303            0.03     Pending                NaN
1304            0.02   Completed                NaN
      sale_id  sale_rep_id   sale_date   car_model  sale_amount  \
1400     1401           11  2024-11-01  Highlander     40400.17
1401     1402           16  2024-11-01       Camry     25528.28
1402     1403           11  2024-11-20     Corolla     20705.85
1403     1404            5  2024-11-07      Tundra     40194.56
1404     1405            1  2024-11-24  Highlander     35642.75

      commission_pct sale_status  commission_amount
1400            0.03   Completed                NaN
1401            0.05   Completed                NaN
1402            0.03   Completed                NaN
1403            0.05     Pending                NaN
1404            0.05   Completed                NaN
      sale_id  sale_rep_id   sale_date   car_model  sale_amount  \
1500     1501           18  2024-11-05      Tundra     41381.86
1501     1502            1  2024-11-18        RAV4     27290.01
1502     1503            3  2024-11-29  Highlander     41047.98
1503     1504           10  2024-11-30      Tundra     45743.25
1504     1505            2  2024-11-06      Tacoma     37943.78

      commission_pct sale_status  commission_amount
1500            0.02   Completed                NaN
1501            0.05   Completed                NaN
1502            0.05     Pending                NaN
1503            0.02   Completed                NaN
1504            0.02   Completed                NaN
      sale_id  sale_rep_id   sale_date car_model  sale_amount  commission_pct  \
1600     1601            5  2024-11-13    Tundra     41455.14            0.05
1601     1602            9  2024-11-12    Tundra     39578.10            0.02
1602     1603            4  2024-11-27   Corolla     20685.84            0.05
1603     1604            7  2024-11-18    Tundra     48682.36            0.02
1604     1605           16  2024-11-30    Tundra     43522.74             NaN

     sale_status  commission_amount
1600   Completed                NaN
1601     Pending                NaN
1602   Completed                NaN
1603   Completed                NaN
1604   Completed                NaN
      sale_id  sale_rep_id   sale_date car_model  sale_amount  commission_pct  \
1700     1701            5  2024-11-05    Tacoma     36385.16            0.02
1701     1702            2  2024-11-14      RAV4     28465.20            0.03
1702     1703            4  2024-11-12   Corolla     20917.69            0.03
1703     1704           13  2024-11-26   Corolla     22037.75            0.03
1704     1705           15  2024-11-24    Tacoma     34978.86             NaN

     sale_status  commission_amount
1700     Pending                NaN
1701   Completed                NaN
1702   Completed                NaN
1703     Pending                NaN
1704   Completed                NaN
      sale_id  sale_rep_id   sale_date   car_model  sale_amount  \
1800     1801            4  2024-11-23      Tundra     45625.11
1801     1802            4  2024-11-08      Tacoma     35063.15
1802     1803           12  2024-11-06      Tundra     47337.31
1803     1804            3  2024-11-03       Camry     29048.33
1804     1805            8  2024-11-10  Highlander     35450.49

      commission_pct sale_status  commission_amount
1800            0.05   Completed                NaN
1801            0.05     Pending                NaN
1802             NaN   Completed                NaN
1803            0.02   Completed                NaN
1804            0.03   Completed                NaN
      sale_id  sale_rep_id   sale_date   car_model  sale_amount  \
1900     1901           18  2024-11-07       Camry     27346.20
1901     1902            3  2024-11-12      Tundra     49974.88
1902     1903           11  2024-11-12      Tacoma     38254.63
1903     1904            8  2024-11-11      Tacoma     31960.77
1904     1905           13  2024-11-04  Highlander     42906.66

      commission_pct sale_status  commission_amount
1900            0.02   Completed                NaN
1901            0.02   Cancelled                NaN
1902            0.02   Completed                NaN
1903            0.02     Pending                NaN
1904            0.02   Completed                NaN
      sale_id  sale_rep_id   sale_date car_model  sale_amount  commission_pct  \
2000     2001           18  2024-11-12   Corolla     23716.87            0.05
2001     2002           10  2024-11-16     Camry     26062.43            0.02
2002     2003           19  2024-11-03   Corolla     21950.57            0.02
2003     2004            9  2024-11-19   Corolla     24548.82            0.03
2004     2005           17  2024-11-30     Camry     27100.00            0.05

     sale_status  commission_amount
2000     Pending                NaN
2001   Completed                NaN
2002   Completed                NaN
2003   Completed                NaN
2004   Completed                NaN
      sale_id  sale_rep_id   sale_date   car_model  sale_amount  \
2100     2101            9  2024-11-13       Camry     28136.48
2101     2102            1  2024-11-22  Highlander     36772.41
2102     2103           20  2024-11-27      Tacoma     37391.60
2103     2104           19  2024-11-17  Highlander     43076.20
2104     2105           20  2024-11-16       Camry     26445.70

      commission_pct sale_status  commission_amount
2100            0.02   Completed                NaN
2101             NaN   Completed                NaN
2102            0.02   Completed                NaN
2103            0.02   Completed                NaN
2104            0.02   Completed                NaN
      sale_id  sale_rep_id   sale_date car_model  sale_amount  commission_pct  \
2200     2201            6  2024-11-07      RAV4     32767.56             NaN
2201     2202            8  2024-11-06    Tacoma     38872.64             NaN
2202     2203           17  2024-11-16    Tacoma     38324.84            0.05
2203     2204           13  2024-11-16      RAV4     32614.83            0.05
2204     2205           20  2024-11-09      RAV4     28049.95            0.05

     sale_status  commission_amount
2200   Completed                NaN
2201   Completed                NaN
2202   Completed                NaN
2203   Completed                NaN
2204   Cancelled                NaN
      sale_id  sale_rep_id   sale_date   car_model  sale_amount  \
2300     2301            1  2024-11-22     Corolla     20716.30
2301     2302            3  2024-11-13        RAV4     27502.39
2302     2303           13  2024-11-10  Highlander     39202.31
2303     2304            7  2024-11-03  Highlander     41036.63
2304     2305            8  2024-11-26      Tundra     35995.19

      commission_pct sale_status  commission_amount
2300            0.05   Completed                NaN
2301            0.03   Completed                NaN
2302            0.03   Completed                NaN
2303            0.05   Completed                NaN
2304            0.02   Completed                NaN
      sale_id  sale_rep_id   sale_date   car_model  sale_amount  \
2400     2401            3  2024-11-26        RAV4     29204.00
2401     2402            1  2024-11-29  Highlander     39334.61
2402     2403            4  2024-11-20      Tundra     41994.63
2403     2404           10  2024-11-14       Camry     27679.98
2404     2405            3  2024-11-28  Highlander     42186.73

      commission_pct sale_status  commission_amount
2400             NaN   Cancelled                NaN
2401             NaN   Completed                NaN
2402            0.05   Cancelled                NaN
2403            0.05   Completed                NaN
2404            0.02   Completed                NaN
      sale_id  sale_rep_id   sale_date   car_model  sale_amount  \
2500     2501           11  2024-11-15  Highlander     37726.80
2501     2502            1  2024-11-08       Camry     26870.93
2502     2503           16  2024-11-05     Corolla     24625.95
2503     2504           11  2024-11-09  Highlander     39172.71
2504     2505           10  2024-11-13  Highlander     35460.40

      commission_pct sale_status  commission_amount
2500            0.03   Completed                NaN
2501            0.05   Completed                NaN
2502            0.03   Completed                NaN
2503             NaN   Cancelled                NaN
2504            0.05   Completed                NaN
      sale_id  sale_rep_id   sale_date   car_model  sale_amount  \
2600     2601            5  2024-11-22  Highlander     36193.13
2601     2602           11  2024-11-02      Tundra     36954.19
2602     2603           13  2024-11-22  Highlander     44481.14
2603     2604           16  2024-11-15     Corolla     22998.98
2604     2605            8  2024-11-27      Tacoma     39389.27

      commission_pct sale_status  commission_amount
2600            0.02   Completed                NaN
2601             NaN     Pending                NaN
2602            0.05     Pending                NaN
2603            0.02   Completed                NaN
2604            0.02   Cancelled                NaN
      sale_id  sale_rep_id   sale_date car_model  sale_amount  commission_pct  \
2700     2701           15  2024-11-13    Tacoma     32112.20            0.03
2701     2702           13  2024-11-21    Tacoma     39982.10            0.02
2702     2703           12  2024-11-18   Corolla     21734.80            0.03
2703     2704           13  2024-11-19   Corolla     21205.50            0.05
2704     2705           17  2024-11-12   Corolla     24809.68            0.05

     sale_status  commission_amount
2700   Completed                NaN
2701   Completed                NaN
2702     Pending                NaN
2703   Completed                NaN
2704   Completed                NaN
      sale_id  sale_rep_id   sale_date car_model  sale_amount  commission_pct  \
2800     2801            8  2024-11-25    Tundra     49138.13            0.05
2801     2802           17  2024-11-18   Corolla     23417.62            0.05
2802     2803           19  2024-11-16    Tacoma     39446.85            0.05
2803     2804           11  2024-11-10    Tundra     41471.81            0.03
2804     2805           13  2024-11-03    Tundra     47656.73            0.05

     sale_status  commission_amount
2800   Completed                NaN
2801     Pending                NaN
2802   Completed                NaN
2803   Completed                NaN

In [97]:
toyata_data_chunk

In [98]:
toyata_data

         1  16  2024-11-18   Tundra  44496.88  0.05  Completed
0        2  11  2024-11-08   Tacoma  34824.72   NaN    Pending
1        3   5  2024-11-03  Corolla  20275.08   NaN  Completed
2        4  20  2024-11-06  Corolla  20068.93   NaN  Completed
3        5   1  2024-11-26   Tundra  49811.99  0.03  Completed
4        6  14  2024-11-28     RAV4  34346.20  0.03  Completed
...    ...  ..         ...      ...       ...   ...        ...
4994  4996   1  2024-11-06  Corolla  21484.83  0.05  Completed
4995  4997   8  2024-11-11    Camry  26519.24  0.05    Pending
4996  4998  18  2024-11-06   Tacoma  30780.39  0.02  Completed
4997  4999  10  2024-11-21  Corolla  22654.59   NaN  Completed
4998  5000  13  2024-11-21   Tundra  44525.85   NaN  Cancelled

[4999 rows x 7 columns]

In [1]:
toyata_data = pd.DataFrame("data-main/car_sales/toyata_sales_data")

NameError: name 'pd' is not defined

In [2]:
import pandas as pd

In [5]:
toyata_data = pd.read_csv("data-main/car_sales/toyota_sales_data.csv")

In [6]:
toyata_data

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status
0,1,16,2024-11-18,Tundra,44496.88,0.05,Completed
1,2,11,2024-11-08,Tacoma,34824.72,NaN,Pending
2,3,5,2024-11-03,Corolla,20275.08,NaN,Completed
3,4,20,2024-11-06,Corolla,20068.93,NaN,Completed
4,5,1,2024-11-26,Tundra,49811.99,0.03,Completed
...,...,...,...,...,...,...,...
4995,4996,1,2024-11-06,Corolla,21484.83,0.05,Completed
4996,4997,8,2024-11-11,Camry,26519.24,0.05,Pending
4997,4998,18,2024-11-06,Tacoma,30780.39,0.02,Completed
4998,4999,10,2024-11-21,Corolla,22654.59,NaN,Completed
4999,5000,13,2024-11-21,Tundra,44525.85,NaN,Cancelled

In [11]:
toyata_data['commission_amt'] = (toyata_data['sale_amount']*toyata_data['commission_pct']).fillna(0).round(2)

In [12]:
toyata_data.head()

,sale_id,sale_rep_id,sale_date,car_model,sale_amount,commission_pct,sale_status,commission_amt
0,1,16,2024-11-18,Tundra,44496.88,0.05,Completed,2224.84
1,2,11,2024-11-08,Tacoma,34824.72,NaN,Pending,0.00
2,3,5,2024-11-03,Corolla,20275.08,NaN,Completed,0.00
3,4,20,2024-11-06,Corolla,20068.93,NaN,Completed,0.00
4,5,1,2024-11-26,Tundra,49811.99,0.03,Completed,1494.36

In [13]:
help(toyata_data.to_csv)

Help on method to_csv in module pandas.core.generic:

to_csv(
    path_or_buf: FilePath | WriteBuffer[bytes] | WriteBuffer[str] | None = None,
    *,
    sep: str = ',',
    na_rep: str = '',
    float_format: str | Callable | None = None,
    columns: Sequence[Hashable] | None = None,
    header: bool | list[str] = True,
    index: bool = True,
    index_label: IndexLabel | None = None,
    mode: str = 'w',
    encoding: str | None = None,
    compression: CompressionOptions = 'infer',
    quoting: int | None = None,
    quotechar: str = '"',
    lineterminator: str | None = None,
    chunksize: int | None = None,
    date_format: str | None = None,
    doublequote: bool = True,
    escapechar: str | None = None,
    decimal: str = '.',
    errors: OpenFileErrors = 'strict',
    storage_options: StorageOptions | None = None
) -> str | None method of pandas.DataFrame instance
    Write object to a comma-separated values (csv) file.

    Parameters
    ----------
    path_or_buf : str, path object, file-like object, or None, default None
        String, path object (implementing os.PathLike[str]), or file-like
        object implementing a write() function. If None, the result is
        returned as a string. If a non-binary file object is passed, it should
        be opened with `newline=''`, disabling universal newlines. If a binary
        file object is passed, `mode` might need to contain a `'b'`.
    sep : str, default ','
        String of length 1. Field delimiter for the output file.
    na_rep : str, default ''
        Missing data representation.
    float_format : str, Callable, default None
        Format string for floating point numbers. If a Callable is given, it takes
        precedence over other numeric formatting parameters, like decimal.
    columns : sequence, optional
        Columns to write.
    header : bool or list of str, default True
        Write out the column names. If a list of strings is given it is
        assumed to be aliases for the column names.
    index : bool, default True
        Write row names (index).
    index_label : str or sequence, or False, default None
        Column label for index column(s) if desired. If None is given, and
        `header` and `index` are True, then the index names are used. A
        sequence should be given if the object uses MultiIndex. If
        False do not print fields for index names. Use index_label=False
        for easier importing in R.
    mode : {{'w', 'x', 'a'}}, default 'w'
        Forwarded to either `open(mode=)` or `fsspec.open(mode=)` to control
        the file opening. Typical values include:

        - 'w', truncate the file first.
        - 'x', exclusive creation, failing if the file already exists.
        - 'a', append to the end of file if it exists.

    encoding : str, optional
        A string representing the encoding to use in the output file,
        defaults to 'utf-8'. `encoding` is not supported if `path_or_buf`
        is a non-binary file object.

    compression : str or dict, default 'infer'
        For on-the-fly compression of the output data. If 'infer' and
        'path_or_buf' is path-like, then detect compression from the following
        extensions: '.gz',
        '.bz2', '.zip', '.xz', '.zst', '.tar', '.tar.gz', '.tar.xz' or '.tar.bz2'
        (otherwise no compression).
        Set to ``None`` for no compression.
        Can also be a dict with key ``'method'`` set to one of
        {``'zip'``, ``'gzip'``, ``'bz2'``, ``'zstd'``, ``'xz'``, ``'tar'``} and
        other key-value pairs are forwarded to
        ``zipfile.ZipFile``, ``gzip.GzipFile``,
        ``bz2.BZ2File``, ``zstandard.ZstdCompressor``, ``lzma.LZMAFile`` or
        ``tarfile.TarFile``, respectively.
        As an example, the following could be passed for faster compression and
        to create a reproducible gzip archive:
        ``compression={'method': 'gzip', 'compresslevel': 1, 'mtime': 1}``.

           May be a dict with key 'method' as compression mode
           and other entries as additional compression options if
           compression mode is 'zip'.

           Passing compression options as keys in dict is
           supported for compression modes 'gzip', 'bz2', 'zstd', and 'zip'.
    quoting : optional constant from csv module
        Defaults to csv.QUOTE_MINIMAL. If you have set a `float_format`
        then floats are converted to strings and thus csv.QUOTE_NONNUMERIC
        will treat them as non-numeric.
    quotechar : str, default '\"'
        String of length 1. Character used to quote fields.
    lineterminator : str, optional
        The newline character or character sequence to use in the output
        file. Defaults to `os.linesep`, which depends on the OS in which
        this method is called ('\\n' for linux, '\\r\\n' for Windows, i.e.).
    chunksize : int or None
        Rows to write at a time.
    date_format : str, default None
        Format string for datetime objects.
    doublequote : bool, default True
        Control quoting of `quotechar` inside a field.
    escapechar : str, default None
        String of length 1. Character used to escape `sep` and `quotechar`
        when appropriate.
    decimal : str, default '.'
        Character recognized as decimal separator. E.g. use ',' for
        European data.
    errors : str, default 'strict'
        Specifies how encoding and decoding errors are to be handled.
        See the errors argument for :func:`open` for a full list
        of options.

    storage_options : dict, optional
        Extra options that make sense for a particular storage connection, e.g.
        host, port, username, password, etc. For HTTP(S) URLs the key-value pairs
        are forwarded to ``urllib.request.Request`` as header options. For other
        URLs (e.g. starting with "s3://", and "gcs://") the key-value pairs are
        forwarded to ``fsspec.open``. Please see ``fsspec`` and ``urllib`` for more
        details, and for more examples on storage options refer `here
        <https://pandas.pydata.org/docs/user_guide/io.html?
        highlight=storage_options#reading-writing-remote-files>`_.

    Returns
    -------
    None or str
        If path_or_buf is None, returns the resulting csv format as a
        string. Otherwise returns None.

    See Also
    --------
    read_csv : Load a CSV file into a DataFrame.
    to_excel : Write DataFrame to an Excel file.

    Examples
    --------
    Create 'out.csv' containing 'df' without indices

    >>> df = pd.DataFrame(
    ...     [["Raphael", "red", "sai"], ["Donatello", "purple", "bo staff"]],
    ...     columns=["name", "mask", "weapon"],
    ... )
    >>> df.to_csv("out.csv", index=False)  # doctest: +SKIP

    Create 'out.zip' containing 'out.csv'

    >>> df.to_csv(index=False)
    'name,mask,weapon\nRaphael,red,sai\nDonatello,purple,bo staff\n'
    >>> compression_opts = dict(
    ...     method="zip", archive_name="out.csv"
    ... )  # doctest: +SKIP
    >>> df.to_csv(
    ...     "out.zip", index=False, compression=compression_opts
    ... )  # doctest: +SKIP

    To write a csv file to a new folder or nested folder you will first
    need to create it using either Pathlib or os:

    >>> from pathlib import Path  # doctest: +SKIP
    >>> filepath = Path("folder/subfolder/out.csv")  # doctest: +SKIP
    >>> filepath.parent.mkdir(parents=True, exist_ok=True)  # doctest: +SKIP
    >>> df.to_csv(filepath)  # doctest: +SKIP

    >>> import os  # doctest: +SKIP
    >>> os.makedirs("folder/subfolder", exist_ok=True)  # doctest: +SKIP
    >>> df.to_csv("folder/subfolder/out.csv")  # doctest: +SKIP

    Format floats to two decimal places:

    >>> df.to_csv("out1.csv", float_format="%.2f")  # doctest: +SKIP

    Format floats using scientific notation:

    >>> df.to_csv("out2.csv", float_format="{{:.2e}}".format)  # doctest: +SKIP

In [14]:
toyata_data.to_csv("data-main/car_sales/toyota_sales_data_commission.csv")